name: Deploy New Version

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name:  deploy
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: GPG Setup
        env:
          GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./gpg-setup.sh
#      - name: Set up JDK 8
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'liberica'
#          java-version: '8'
#          java-package: jdk
#      - name: Deploy to OSS Sonatype
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
#          OSS_SONATYPE_TOKEN: ${{ secrets.OSS_SONATYPE_TOKEN }}
#        run: mvn -B -Prelease,jdk-17,jdk-8 source:jar javadoc:jar deploy --file pom.xml -s settings-template.xml -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'
          java-package: jdk
      - name: Deploy to OSS Sonatype
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          OSS_SONATYPE_TOKEN: ${{ secrets.OSS_SONATYPE_TOKEN }}
        run: mvn -B -Prelease source:jar javadoc:jar deploy --file pom.xml -s settings-template.xml -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
